apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  labels:
    env: prod
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  labels:
    env: prod
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 3Gi